name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  php-v:
    runs-on: ubuntu-latest
    container:
      image: php:8.0.0alpha2-cli-buster
    steps:
      - uses: actions/checkout@v1
      - run: php -v
